/**
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at http://mozilla.org/MPL/2.0/. OpenMRS is also distributed under
 * the terms of the Healthcare Disclaimer located at http://openmrs.org/license.
 *
 * Copyright (C) OpenMRS Inc. OpenMRS is a registered trademark and the OpenMRS
 * graphic logo is a trademark of OpenMRS Inc.
 */
package org.openmrs.module.poc.testrequest.util;

import java.util.Arrays;
import java.util.EnumMap;
import java.util.List;

import org.openmrs.module.poc.api.common.util.OPENMRSUUIDs;

public class MappedLaboratoryGeralSet {
	
	private static EnumMap<LaboratoryGeralSets, List<String>> labSets = new EnumMap<>(LaboratoryGeralSets.class);
	
	static {
		
		MappedLaboratoryGeralSet.labSets.put(LaboratoryGeralSets.HEMOGRAMA_KX21N,
		    Arrays.asList(
		        OPENMRSUUIDs.WHITE_BLOOD_CELLS_CONCEPT_UUID,
		        OPENMRSUUIDs.RED_BLOOD_CELLS_CONCEPT_UUID,
		        OPENMRSUUIDs.HEMOGLOBIN_CONCEPT_UUID,
		        OPENMRSUUIDs.HEMATOCRIT_CONCEPT_UUID,
		        OPENMRSUUIDs.MEAN_CORPUSCULAR_VOLUME_CONCEPT_UUID,
		        OPENMRSUUIDs.MEAN_CORPUSCULAR_HEMOGLOBIN_CONCEPT_UUID,
		        OPENMRSUUIDs.MEAN_CELL_HEMOGLOBIN_CONCENTRATION_CONCEPT_UUID,
		        OPENMRSUUIDs.PLATELETS_CONCEPT_UUID,
		        OPENMRSUUIDs.RED_CELL_DISTRIBUTION_WIDTH_CONCEPT_UUID,
		        OPENMRSUUIDs.ERYTHROCYTE_SEDIMENTATION_RATE_CONCEPT_UUID,
		        OPENMRSUUIDs.MEAN_PLATELET_VOLUME_CONCEPT_UUID,
		        OPENMRSUUIDs.BLOOD_TYPING_CONCEPT_UUID,
		        OPENMRSUUIDs.LYMPHOCYTES_CONCEPT_UUID,
		        OPENMRSUUIDs.ABSOLUTE_LYMPHOCYTE_COUNT_CONCEPT_UUID,
		        OPENMRSUUIDs.NEUTROPHILS_CONCEPT_UUID,
		        OPENMRSUUIDs.ABSOLUTE_NEUTROPHIL_COUNT_CONCEPT_UUID,
		        OPENMRSUUIDs.EOSINOPHILS_CONCEPT_UUID,
		        OPENMRSUUIDs.ABSOLUTE_EOSINOPHIL_COUNT_CONCEPT_UUID,
		        OPENMRSUUIDs.BASOPHILS_CONCEPT_UUID,
		        OPENMRSUUIDs.ABSOLUTE_BASOPHIL_COUNT_CONCEPT_UUID,
		        OPENMRSUUIDs.MONOCYTES_CONCEPT_UUID,
		        OPENMRSUUIDs.ABSOLUTE_MONOCYTE_COUNT_CONCEPT_UUID,
		        OPENMRSUUIDs.VDRL_CONCEPT_UUID
		            ));
		
		MappedLaboratoryGeralSet.labSets.put(LaboratoryGeralSets.IMMUNOLOGIA, Arrays.asList(
		    OPENMRSUUIDs.RAPID_PLASMA_REAGIN_CONCEPT_UUID,
		    OPENMRSUUIDs.CD4_COUNT_CONCEPT_UUID,
		    OPENMRSUUIDs.CD4_PERCENT_CONCEPT_UUID));
		
		MappedLaboratoryGeralSet.labSets.put(LaboratoryGeralSets.TESTAGEM_VIROLOGIA, Arrays.asList(
		        OPENMRSUUIDs.HIV_VIRAL_LOAD_CONCEPT_UUID));
		
		MappedLaboratoryGeralSet.labSets.put(LaboratoryGeralSets.BIOQUIMICA_LABORATORIO, Arrays.asList(
		    OPENMRSUUIDs.ALKALINE_PHOSPHATASE_CONCEPT_UUID,
		    OPENMRSUUIDs.AMYLASE_CONCEPT_UUID,
		    OPENMRSUUIDs.BLOOD_UREA_NITROGEN_CONCEPT_UUID,
		    OPENMRSUUIDs.CREATINE_KINASE_CONCEPT_UUID,
		    OPENMRSUUIDs.DIRECT_BILIRUBIN_CONCEPT_UUID,
		    OPENMRSUUIDs.GAMMA_GLUTAMYL_TRANSFERASE_CONCEPT_UUID,
		    OPENMRSUUIDs.GLOBULINS_CONCEPT_UUID,
		    OPENMRSUUIDs.HIGH_DENSITY_LIPOPROTEIN_CHOLESTEROL_CONCEPT_UUID,
		    OPENMRSUUIDs.LACTATE_DEHYDROGENASE_CONCEPT_UUID,
		    OPENMRSUUIDs.LOW_DENSITY_LIPOPROTEIN_CHOLESTEROL_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_ALBUMIN_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_CHLORIDE_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_CREATININE_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_GLUCOSE_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_GLUTAMIC_OXALOACETIC_TRANSAMINASE_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_GLUTAMIC_PYRUVIC_TRANSAMINASE_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_LACTATE_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_LIPASE_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_POTASSIUM_CONCEPT_UUID,
		    OPENMRSUUIDs.SERUM_SODIUM_CONCEPT_UUID,
		    OPENMRSUUIDs.TOTAL_BILIRUBIN_CONCEPT_UUID,
		    OPENMRSUUIDs.TOTAL_CHOLESTEROL_CONCEPT_UUID,
		    OPENMRSUUIDs.TOTAL_PROTEIN_CONCEPT_UUID,
		    OPENMRSUUIDs.TRIGLYCERIDES_CONCEPT_UUID));
		
		MappedLaboratoryGeralSet.labSets.put(LaboratoryGeralSets.PCR, Arrays.asList(
		        OPENMRSUUIDs.HIV_DNA_POLYMERASE_CHAIN_REACTION_QUALITATIVE_CONCEPT_UUID));
		
		MappedLaboratoryGeralSet.labSets.put(LaboratoryGeralSets.TUBERCULOSIS_EXAMS_SET, Arrays.asList(
		        OPENMRSUUIDs.SPUTUM_FOR_ACID_FAST_BACILLI_CONCEPT_UUID));
	}
	
	public static List<String> getLaboratoryConceptTests(final LaboratoryGeralSets labSetKey) {
		return MappedLaboratoryGeralSet.labSets.get(labSetKey);
	}
}
